name: PR Quality Check

on: [pull_request]

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: |
          echo "Will add code checks here in next challenge"
